#Print Hello Message Inside a container
FROM ubuntu:20.04
#MAINTAINER
LABEL maintainer="bhupendra.jmd@gmail.com"
#print your name
CMD ["echo", "Hello World from Docker"]
#CMD echo "Iot-Feb-2020 batch"
